name: 'Terraform'
on:
  push:
    branches:
      - main
  pull_request:

env:
  tf_version: 1.1.8
  tflint_version: v0.39.3

concurrency:
  group: cicd-pipeline-${{ github.workflow }}-${{ github.event.pull_request.number || github.event.pull_request.head.ref || github.ref }}

jobs:
  linters:
    name: 'Terraform Linters'
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      security-events: write
    defaults:
      run:
        shell: bash
    steps:
      -
        name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.tf_version }}
          terraform_wrapper: false
      -
        name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.38.1
      -
        name: Setup TFLint cache plugin dir
        uses: actions/cache@v4.2.3
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      -
        name: Test code with TFLint
        run: |
          tflint --init
          tflint -f compact
      -
        name: Test code with TFSec
        uses: aquasecurity/tfsec-sarif-action@v0.1.4
        with:
          sarif_file: tfsec.sarif
  semver:
    name: 'Set code version tag'
    runs-on: ubuntu-24.04
    needs:
      - linters
    defaults:
      run:
        shell: bash
    steps:
      -
        name: Check out code
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      -
        name: Check out code
        uses: actions/checkout@v3
        if: github.event_name == 'push'
        with:
          fetch-depth: 0
      -
        name: Set application version
        id: set_version
        uses: kvendingoldo/git-flow-action@v2.0.2
        with:
          enable_github_release: true
          auto_release_branches: "main"
          tag_prefix_release: "v"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
