name: 'Terraform'
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    env:
      tf_version: 1.1.8
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.tf_version }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt --recursive -check=true --diff
        continue-on-error: true
      -
        name: Set application version
        id: set_version
        uses: kvendingoldo/semver-action@v1.10
        with:
          primary_branch: main